# Generated by Django 3.2 on 2022-07-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220709_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=None, max_length=254, null=True, unique=True),
        ),
    ]
